click until text step
qavajs/steps-playwright pull request #126
Opened 2024-07-15 11:34 UTC by ALegchilov

## Description

Please describe your changes and any new features you're introducing, or issues you're fixing.

- [ ] Updated the CHANGELOG.md.
- [ ] Updated package version in package.json, package-lock.json.
- [ ] Checked that there aren't other open pull requests for the same issue/update.
- [ ] Checked that your contribution follows the project's contribution guidelines.
- [ ] Added corresponding unit/E2E tests
- [ ] Unit and E2E pass

### Related Issues

Please link any related issues or bug reports that this PR will address.

2024-07-15 16:26 UTC, AlexGalichenko requested changes

2024-07-16 09:06 UTC, ALegchilov commented on src/IQavajsPlaywrightConfig.ts
> +    present?: number,
Coud you check now?

2024-07-17 06:13 UTC, AlexGalichenko requested changes

2024-07-17 06:13 UTC, AlexGalichenko commented on src/waits.ts
> +        {timeout, interval: defaultTimeouts.actionInterval},
here default timeout should be imported from config

2024-07-17 06:13 UTC, AlexGalichenko commented on utils.d.ts
> +export function getConditionWait(condition: string): (element: Locator) => Promise<Function>;
Promise<void>

2024-07-17 06:13 UTC, AlexGalichenko commented on src/waits.ts
> +            {timeout, interval: defaultTimeouts.actionInterval},
here default timeout should be imported from config

2024-07-17 06:52 UTC, AlexGalichenko approved these changes

2024-07-17 07:12 UTC, KirillBogdanets commented on src/IQavajsPlaywrightConfig.ts
> +      pageRefreshInterval: number
why is it the only mandatory property?

2024-07-17 07:23 UTC, ALegchilov commented on src/IQavajsPlaywrightConfig.ts
> +      pageRefreshInterval: number
Good catch. It's optional indeed.

2024-07-17 09:13 UTC, ALegchilov commented on utils.d.ts
> +export function getConditionWait(condition: string): (element: Locator) => Promise<Function>;
Agreed to declare it as Promise<void>

2024-07-17 09:28 UTC, merged